### ISSUE TITLE
"TypeError: Attempted to assign to readonly property" in Safari

### ISSUE THREAD

**Issue by kaueburiti** [aesqe/mapboxgl-minimap#1]
I'm getting this follow error when using the mapboxgl-minimap in Safari:

<img width="748" alt="screen shot 2017-01-09 at 08 31 43" src="https://cloud.githubusercontent.com/assets/4473734/21765209/255c47dc-d646-11e6-9f8a-cbf3f8d6875a.png">

As you can see, the error occurs in the `onAdd` method, more specifically in this line: `var container = this._container = this._createContainer(parentMap)`.
If I disallow the strict mode, the Safari stops from alerting about the TypeError, but the minimap does not works, anyway.

This error occurs just in Safari, I have tested on Chrome, Firefox and Opera and I got no error.

**Comment by kaueburiti** [comment]
Solution here: https://github.com/aesqe/mapboxgl-minimap/pull/2

**Comment by aesqe** [comment]
Fixed in #2
