### ISSUE TITLE
TypeError: Cannot read property 'inherit' of undefined

### ISSUE THREAD

**Issue by gabimoncha** [aesqe/mapboxgl-minimap#3]
When trying to use the minimap in react, it returns me this error:
```
mapboxgl-control-minimap.js:17 Uncaught TypeError: Cannot read property 'inherit' of undefined
```

Line 17: `Minimap.prototype = mapboxgl.util.inherit(mapboxgl.Control, { options`

is it because the mapbox version is too old?

**Comment by loker** [comment]
I've tried to remake the demo itself with the latest mapbox version and had the error:
TypeError: mapboxgl.util is undefined  (mapbox.MiniMap.js:15:1)
TypeError: mapboxgl.Minimap is not a constructor

If I use the version in the example it works but it's too old really.

**Comment by gabimoncha** [comment]
Don't worry. I managed to rebuild it myself through a react component :)
