### ISSUE TITLE
Publish on NPM?

### ISSUE THREAD

**Issue by patrickcate** [aesqe/mapboxgl-minimap#7]
It would be great if this was published as an NPM package. It would make installing it much easier.

**Comment by aesqe** [comment]
@patrickcate @nmacneil @rek Published on NPM, sorry for the long wait! 🙂 🤦 https://www.npmjs.com/package/@aesqe/mapboxgl-minimap

**Comment by rek** [comment]
Excellent thanks! 

...though we ended up making our own copy adding in some of the work done on the forks.
